### ISSUE TITLE
Install Problems on Moodle 4.0.2

### ISSUE THREAD

**Issue by bkasel** [center-for-learning-management/moodle-block_edupublisher#53]
Dear maintainers,

I have some trouble installing the edupublisher block on my moodle 4.0.2 site. 

When I try to upgrade the moodle database, I get the following error. I don't have substantial PHP/SQL knowledge, so it is difficult for me to assess if this is a bug or a configuration problem on my side.

Kind Regards
![grafik](https://user-images.githubusercontent.com/16179803/179388058-84bf9bee-305c-4d91-a066-b91b4c33e674.png)

**Comment by rschrenk** [comment]
Thanks for your bug report. Indeed it seems, that I missed some primary keys in the install.xml.
Can you please test the installation with the current master of the repository (or just replace the install.xml in your installation).

If this fixes the problem, I will release a new version on moodle.org

**Comment by bkasel** [comment]
Hello,

There still seems to be a problem, but a different one:
![grafik](https://user-images.githubusercontent.com/16179803/180087584-5f25a82b-eb30-40fe-a06c-19c98d13de11.png)

**Comment by rschrenk** [comment]
This is indeed also a problem. I fixed this in the upgrade.php (https://github.com/center-for-learning-management/moodle-block_edupublisher/blob/5a1a24975d5408ac76abf2f0d3aebfca473d0d16/db/upgrade.php#L683), but forgot to fix in install.xml.

The problem is, that Moodle does not allow to add indices on text-fields, although it is technically possible (and advisable in this case). I added the indices later directly in the database, which was no problem.
![indices](https://user-images.githubusercontent.com/8080807/180142040-9d36ff62-594c-485b-985b-33fcff51d2d3.jpg)

However, I change the install.xml, so that the installation will not fail and added the information in the README.

Can you please try again?

**Comment by bkasel** [comment]
Yes it works!
![grafik](https://user-images.githubusercontent.com/16179803/180284526-bebd7f5e-7df8-4937-b3fe-244391362ba5.png)

Thank you for the quick fixes

**Comment by rschrenk** [comment]
great!
